version: '3.8'

services:
  rest-api:
    container_name: tglab_rest_api
    build:
      context: .
      dockerfile: ./BackEnd/TgLab.API/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: tglab_database
    environment:
      - SA_PASSWORD=strong*password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: